services:
  ollama:
    image: ollama/ollama:0.20.6
    volumes:
      - ./bin/ollama:/root/.ollama
      - ./ollama_setup.sh:/ollama_setup.sh
    ports:
      - "11434:11434"
    restart: always
    entrypoint: [ "/usr/bin/bash", "/ollama_setup.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  sd:
    image: universonic/stable-diffusion-webui:full
    command: --medvram --api
#    command: --lowvram --api # replace with this if your PC is a potato
    restart: always
    ports:
      - "7860:8080/tcp"
    volumes:
      - ./bin/sd/inputs:/app/stable-diffusion-webui/inputs
      - ./bin/sd/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - ./bin/sd/embeddings:/app/stable-diffusion-webui/embeddings
      - ./bin/sd/extensions:/app/stable-diffusion-webui/extensions
      - ./bin/sd/models:/app/stable-diffusion-webui/models
      - ./bin/sd/localizations:/app/stable-diffusion-webui/localizations
      - ./bin/sd/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

# uncomment below if you want a dashboard with stats
#
#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./bin/prometheus/data:/prometheus
#    ports:
#      - "9090:9090"
#    restart: always
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
##      - '--web.enable-admin-api'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#  grafana:
#    image: grafana/grafana:latest
#    volumes:
#      - ./bin/grafana/data:/var/lib/grafana
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
#      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yaml
#      - ./grafana/datasources:/etc/grafana/provisioning/datasources
#    ports:
#      - "3000:3000"
#    restart: always
#    depends_on:
#      - prometheus
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin # IMPORTANT: change this
#      - GF_USERS_ALLOW_SIGN_UP=false