#pragma once
#include "IOpenAIChat.h"
#include "OpenAITools.h"
#include "Endpoint.h"

#include <memory>
#include <functional>

namespace proxy_server {

using ToolFactory = std::function<OpenAITools(IOpenAIChat::Session messages)>;

struct Config {
    Endpoint upstreamEndpoint;
    int port = 10434;
    ToolFactory toolsFactory;
};

class IProxyServer {
public:
    virtual ~IProxyServer() = default;
    virtual void waitUntilReady() = 0;

    /**
     * @brief Called after every completed request to the LLM.
     * @details
     * Allows the caller (e.g. AppBase) to persist the proxy session context to the diary.
     *
     * The JSON object contains a OpenAI request to the LLM, structurally similar to `OpenAIChatImpl::makeQueryString`.
     *
     * This JSON itself is generated by the client connected to the proxy, however its altered by the proxy by appending
     * tools calls hidden to the client.
     */
    emits<AJson> sentRequestToLLM;
};

std::shared_ptr<IProxyServer> init(Config config = {});

}   // namespace proxy_server