#pragma once
#include "AUI/Common/AObject.h"
#include "AUI/Common/ATimer.h"
#include "AUI/Thread/AAsyncHolder.h"
#include "AUI/Thread/AEventLoop.h"
#include "Diary.h"
#include "IOpenAIChat.h"
#include "MetricsBreadcumbs.h"
#include "OpenAITools.h"

class AppBase : public AObject {
public:
    struct Init {
        APath workingDir = "test_data";
        _<IOpenAIChat> openAI;
    };
    AppBase(Init init);
    static AString getSystemPrompt();

    struct Notification {
        AString message;
        OpenAITools actions;
        AFuture<> onStartedProcessing;
        AFuture<> onProcessed;
    };


    /**
     * @brief Passes an event to the AI to process
     * @param notification notification text message in natural language (i.e., "you received a message from "...": ...;
     * an
     * @param actions immediate actions (tools) related to the notification (i.e., open related chat)
     * alarm triggerred, etc...)
     * @return Promise satisfied when the notification is processed.
     * @details
     * Think of it as your phone's notifications: you receive a notification, read it and (maybe) react to it.
     */
    const Notification& passNotificationToAI(AString notification, OpenAITools actions = {}, bool first = false);

    AFuture<> diaryDumpMessages();

    void actProactively();

    [[nodiscard]] const IOpenAIChat::Session& temporaryContext() const { return mTemporaryContext; }

    [[nodiscard]] Diary& diary() { return mDiary; }

    /**
     * @brief True when currently processing notification generated by actProactively.
     */
    [[nodiscard]] bool isActingProactively() const { return mActingProactively; }

    struct ToolCallEvent {
        AString toolName;
        AMap<AString, AString> breadcrumbLabels;
        AOptional<std::chrono::seconds> lastOpenedChatLastMessageTime;
    };
    emits<ToolCallEvent> toolCallFired;

    [[nodiscard]]
    const _<MetricsBreadcumbs>& metricBreadcumbs() const {
        return mMetricBreadcumbs;
    }

    /**
     * @brief If Kuni is sleeping, this function wake ups her.
     */
    void wakeUpIfSleeping() {
        mWakeup = true;
    }

protected:
    AAsyncHolder mAsync;
    aui::float_within_0_1 mRelevanceThreshold = 0.5f;

    // Set by llmuiOpenTelegramChat; read by updateTools to populate ToolCallEvent.
    AOptional<std::chrono::system_clock::time_point> mLastOpenedChatLastMessageTime;

    virtual AFuture<AString> onCleanContext();


    /**
     * @brief Called by the main coroutine when a notification was processed.
     */
    virtual void onOffline() {}

    /**
     * @brief Called by the main coroutine during LLM inference streaming to observe which tool calls LLM is about to
     * perform.
     * @details
     * Can be used to send typing action as soon as send_telegram_message tool call appears in tools.
     */
    virtual void onResponseAssembling(IOpenAIChat::Response response) {}

    /**
     *
     * @return @brief Called before LLM's processing loop.
     */
    virtual AFuture<> onBeforeMainLoop() { co_return; }

    /**
     * @brief Adds always available actions
     */
    virtual void updateTools(OpenAITools& actions);

    /**
     * @brief Removes notifications by the given substring.
     * @param substring to search in notification texts. Must be unique enough to avoid false positives.
     * @details
     * Can be used to remove obsolete notifications from AI's queue.
     */
    void removeNotifications(const AString& substring);

    IOpenAIChat::Session mTemporaryContext = [] {
        IOpenAIChat::Session s;
        s.sessionId = "kuni_main_coro";
        return s;
    }();

    /**
     * @brief Performs needed adjustments to the diary page and removes the page from listing. Formatted contents are
     * returned.
     * @details
     * Adjusts usage count, last used and score fields, according to relatedness.
     *
     * Format's with XML tag with needed attributes.
     *
     * The diary page with new metadata is dropped onto disk and removes from mDiary. This ensures this specific diary
     * page wouldn't be considered and included again until mTemporary context is cleaned via diaryDumpMessages.
     *
     */
    [[nodiscard]]
    AString takeDiaryEntry(const Diary::EntryExAndRelatedness& i);

    [[nodiscard]]
    const _<IOpenAIChat>& openAI() const noexcept {
        return mInit.openAI;
    }

private:
    _<MetricsBreadcumbs> mMetricBreadcumbs = _new<MetricsBreadcumbs>();
    const Init mInit;
    std::deque<Notification> mNotifications;
    AFuture<> mNotificationsSignal;
    _<ATimer> mWakeupTimer;
    // OpenAITools mTools;

    bool mWakeup = false;

    /**
     * @brief True when currently processing notification generated by actProactively.
     */
    bool mActingProactively = false;

    /**
     * @brief True if #ask was called at least once during the current notification processing turn.
     * Reset at the start of each notification, set via onAfterToolCall.
     */
    bool mAskCalledThisTurn = false;

    Diary mDiary;
};
